### ISSUE TITLE
Doesn't work on Anki 2.1.26

### ISSUE THREAD

**Issue by Nanco300** [RisingOrange/anki-enhanced-cloze#4]
Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-08-10 19:37:08
Extensões possivelmente envolvidas: ⁨Enhanced Cloze for Anki 21⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 43, in handler
  File "aqt/main.py", line 199, in setupProfile
  File "aqt/main.py", line 398, in loadProfile
  File "aqt/gui_hooks.py", line 1559, in __call__
  File "anki/hooks.py", line 583, in runHook
  File "/home/maquiavelho/.local/share/Anki2/addons21/1990296174/enhanced_cloze.py", line 238, in addModel
    model = mm.by_name(MODEL_NAME)
AttributeError: 'ModelManager' object has no attribute 'by_name'

**Comment by Nanco300** [comment]
Occurs error when access panel:

Informação de Debug:
Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-08-10 19:37:08
Extensões possivelmente envolvidas: ⁨Enhanced Cloze for Anki 21, Cloze Hide All, Blitzkrieg II - Advanced Browser Sidebar BETA8⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 43, in handler
  File "/home/maquiavelho/.local/share/Anki2/addons21/564851917/sidebar21.py", line 96, in <lambda>
    25, lambda:self._timedItemClick(item, True), False
  File "/home/maquiavelho/.local/share/Anki2/addons21/564851917/sidebar21.py", line 100, in _timedItemClick
    item.onClick()
  File "aqt/browser.py", line 1252, in <lambda>
  File "aqt/browser.py", line 1239, in setFilter
  File "aqt/browser.py", line 769, in onSearchActivated
  File "</home/maquiavelho/Documents/Vinicius/Programas/anki-2.1.26-linux-amd64/bin/decorator.pyc:decorator-gen-34>", line 2, in saveNow
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/home/maquiavelho/.local/share/Anki2/addons21/1709973686/main.py", line 89, in beforeSaveNow
    return _old(self, newCallback, keepFocus)
  File "aqt/editor.py", line 474, in saveNow
  File "aqt/editor.py", line 577, in saveTags
  File "anki/notes.py", line 85, in flush
  File "anki/notes.py", line 206, in _preFlush
  File "anki/hooks.py", line 350, in __call__
  File "/home/maquiavelho/.local/share/Anki2/addons21/1990296174/enhanced_cloze.py", line 189, in maybe_generate_enhanced_cloze
    if note and note.note_type()["name"] == MODEL_NAME:
AttributeError: 'Note' object has no attribute 'note_type'

**Comment by Nanco300** [comment]
Do The development to Anki 2.1.26 continues?

**Comment by RisingOrange** [comment]
Yes, it will probably be there in the next few days.

**Comment by RisingOrange** [comment]
The newest update of the add-on works on Anki 2.1.28+ 
Can you maybe update Anki to this version? I currently do not plan to make it work on 2.1.26, it would require more time than I want to invest in this.

**Comment by Nanco300** [comment]
> The newest update of the add-on works on Anki 2.1.28+
> Can you maybe update Anki to this version? I currently do not plan to make it work on 2.1.26, it would require more time than I want to invest in this.

Some addons don't work in 2.1.28.

**Comment by Nanco300** [comment]
If I create cards with the addon failing and then disable it, then did the cards created work?

**Comment by RisingOrange** [comment]
I'm not sure I know what you mean. When you create cards with the add-on and then disable the add-on, the cards will still work, but if you edit them later, they will break.

**Comment by Nanco300** [comment]
> I'm not sure I know what you mean. When you create cards with the add-on and then disable the add-on, the cards will still work, but if you edit them later, they will break.

Thank you

**Comment by Nanco300** [comment]
> > The newest update of the add-on works on Anki 2.1.28+
> > Can you maybe update Anki to this version? I currently do not plan to make it work on 2.1.26, it would require more time than I want to invest in this.
> 
> Some addons don't work in 2.1.28.

Hi, a have update the addon Pop-up Dictionary and seems that errors I reported disappear.

**Comment by Nanco300** [comment]
Please, add this addon for Anki 2.1.26

**Comment by RisingOrange** [comment]
Sorry, Anki versions 2.1.26 and lower have a whole different way of handling clozes and I would have to rewrite most of the addon to make it work.
